------------------------------------------------------------------------
--- Modulo che definisce i guasti del sistema: interruzione per      ---
--- failure della macchina e blocco per buffer di output saturo      ---
------------------------------------------------------------------------

mod FAILURES is
  protecting TRANSPORT .

  var SId : StationId .
  vars B1 B2 : Buffer .

  --- guasto macchina
  rl [machine-failure] :
    < SId, processing, B1, B2 >
    =>
    < SId, fail, B1, B2 > .

  --- blocco per buffer pieno
  crl [blocked-output] :
    < SId, processing, B1, B2 >
    =>
    < SId, blocked, B1, B2 >
    if isFull(B2) .
endm
