------------------------------------------------------------------------
--- Modulo che definisce le regole di lavorazione locale di una      ---
--- stazione: avvio, completamento e ritorno allo stato idle         ---
------------------------------------------------------------------------

mod PROCESSING is
  protecting INIT .

  var SId : StationId .
  vars BIn BOut : Buffer .
  vars L L2 : PalletList .
  vars C1 C2 : Nat .
  var PID : PalletId .
  var T : ProductType .

  --- avvio lavorazione
  rl [start-processing] :
    < SId, idle, buffer(p(PID, T) ; L, C1), BOut >
    =>
    < SId, processing, buffer(L, C1), BOut > .

  --- fine lavorazione: sposta pallet lavorato nel buffer di output
  crl [finish-processing] :
    < SId, processing, buffer(p(PID, T) ; L, C1), buffer(L2, C2) >
    =>
    < SId, unload, buffer(L, C1), buffer(p(PID, T) ; L2, C2) >
    if size(L2) < C2 .

  --- torna idle dopo scarico
  rl [back-idle] :
    < SId, unload, BIn, BOut >
    =>
    < SId, idle, BIn, BOut > .
endm
