-----------------------------------------------------------------------
--- Modulo che definisce le regole di ripristino del sistema:       ---
--- riparazione di una macchina in fail e sblocco di una macchina   ---
--- in stato blocked                                                ---
-----------------------------------------------------------------------

mod RECOVERY is
  protecting INIT .

  var SId : StationId .
  vars B1 B2 : Buffer .

  --- ripristino macchina
  rl [repair-machine] :
    < SId, fail, B1, B2 >
    =>
    < SId, idle, B1, B2 > .

  --- sblocco macchina
  rl [unblock-machine] :
    < SId, blocked, B1, B2 >
    =>
    < SId, idle, B1, B2 > .
endm
