--------------------------------------------------------------------------
--- Modulo che modella il vincolo di sincronizzazione: una stazione    ---
--- non può avviare la lavorazione se il proprio buffer di output      ---
--- è pieno, transitando nello stato blocked                           ---
--------------------------------------------------------------------------

mod SYNCHRONIZATION is
  protecting RECOVERY .

  var SId : StationId .
  vars B1 B2 : Buffer .

  --- una stazione non può iniziare se output pieno
  crl [cannot-start-if-output-full] :
    < SId, idle, B1, B2 >
    =>
    < SId, blocked, B1, B2 >
    if isFull(B2) .
endm
