mod TRANSITIONS is
  protecting STATE .
  protecting TYPES .
  protecting STATION .
  protecting BUFFER .
  protecting CONFIG .

  vars SId1 SId2 SId : StationId .
  vars BIn1 BOut1 BIn2 BOut2 BIn BOut : Buffer .

  crl [sync-S1-S2] :
    < SId1, unload, BIn1, BOut1 > < SId2, idle, BIn2, BOut2 >
    =>
    < SId1, unload, BIn1, BOut1 > < SId2, processing, BIn2, BOut2 >
    if true .

  rl [reset-all-idle] :
    < SId, fail, BIn, BOut > => < SId, idle, BIn, BOut > .

  rl [unblock-all] :
    < SId, blocked, BIn, BOut > => < SId, idle, BIn, BOut > .
endm
