---------------------------------------------------------------------------
--- Modulo che definisce la Configurazione globale del sistema come     ---
--- insieme di stazioni e pallet, con operatore associativo-commutativo ---
---------------------------------------------------------------------------

mod CONFIG is
  protecting STATION .
  protecting PALLET .

  sort Config .

  subsorts Station Pallet < Config .

  op none : -> Config .
  op __ : Config Config -> Config [assoc comm id: none] .
endm
