mod INIT is
  protecting VALIDATION .

  op init : -> Config .

  eq init =
      < S1,
        idle,
        buffer(p(P1, T1) ; p(P2, T1) ; p(P3, T1) ; p(P4, T1), 5),
        buffer(empty, 5) >

      < S2,
        idle,
        buffer(empty, 4),
        buffer(empty, 4) >

      < S3,
        idle,
        buffer(empty, 5),
        buffer(empty, 5) >

      < S4,
        idle,
        buffer(empty, 5),
        buffer(empty, 5) >

      < S5,
        idle,
        buffer(empty, 4),
        buffer(empty, 4) > .
endm
