------------------------------------------------------------------------------------
--- Modulo per verificare che il numero di Pallet rimane invariato in ogni stato ---
------------------------------------------------------------------------------------

--- verifica con 'red in CONSERVATION : modelCheck(init, [] conserved) .' ---

mod CONSERVATION-VER is
  protecting SYSTEM .
  protecting VALIDATION .
  including SATISFACTION .

  subsort Config < State .

  op conserved : -> Prop .

  var C : Config .
  eq C |= conserved = (countPallets(C) == 4) .
endm

mod CONSERVATION is 
  including CONSERVATION-VER .
  including MODEL-CHECKER .
  including LTL-SIMPLIFIER .
endm