--------------------------------------------------------------
--- Modulo per verificare l'assenza di overflow nei Buffer ---
--------------------------------------------------------------

mod NO-OVERFLOW is
  protecting CONFIG .
  protecting TYPES .

  op checkNoOverflow : Config -> Bool .
  op bufferNoOverflow : Buffer -> Bool .

  var CF : Config .
  var SId : StationId .
  var MS : MachineState .
  vars B1 B2 B : Buffer .

  --- funzione ausiliaria: usa cap (getter definito in BUFFER)
  eq bufferNoOverflow(B) = size(content(B)) <= cap(B) .

  --- controllo che nessun buffer in una configurazione sia in overflow
  eq checkNoOverflow(none) = true .
  eq checkNoOverflow(< SId, MS, B1, B2 > CF) =
    bufferNoOverflow(B1) and bufferNoOverflow(B2) and checkNoOverflow(CF) .
endm
